// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBiB1dEAX__kGD0EHhmhyt4I6p7_dubjY',
    appId: '1:19205980163:web:5732d16541791caae54e36',
    messagingSenderId: '19205980163',
    projectId: 'on-time-74859',
    authDomain: 'on-time-74859.firebaseapp.com',
    storageBucket: 'on-time-74859.appspot.com',
    measurementId: 'G-VM44C9VJQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNOcpw1FXkYFyU8H1aj3sdEWEhnuiTXwQ',
    appId: '1:19205980163:android:3f771b19a808732be54e36',
    messagingSenderId: '19205980163',
    projectId: 'on-time-74859',
    storageBucket: 'on-time-74859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKmeFu0Ur5Cntnoz9pd4XNthrzkzEmoI',
    appId: '1:19205980163:ios:b33d9d8beb98037de54e36',
    messagingSenderId: '19205980163',
    projectId: 'on-time-74859',
    storageBucket: 'on-time-74859.appspot.com',
    iosClientId: '19205980163-n3d5copbhuiet7npl006fg8hhl1vc3d0.apps.googleusercontent.com',
    iosBundleId: 'com.zari.bytrh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuKmeFu0Ur5Cntnoz9pd4XNthrzkzEmoI',
    appId: '1:19205980163:ios:b33d9d8beb98037de54e36',
    messagingSenderId: '19205980163',
    projectId: 'on-time-74859',
    storageBucket: 'on-time-74859.appspot.com',
    iosClientId: '19205980163-n3d5copbhuiet7npl006fg8hhl1vc3d0.apps.googleusercontent.com',
    iosBundleId: 'com.zari.bytrh',
  );
}
